name: build-ipk
on:
  push:
    tags:
      - v*
    branches:
      - github_actions
jobs:
  package:
    name: Package release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          ls -lah
          pwd
