name: build-ipk
on:
  push:
    tags:
      - v*
jobs:
  package:
    name: Package release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ./docker-build.sh
